### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by alecherryy** [alecherryy/cooks-books-app#12]
The Footer layout includes a wide Constrain and a content field; content shall align left and include the following:
1. A link to the Privacy Policy page
2. Small text and a Link to the GitHub page.

Sketch: [Page](https://www.sketch.com/s/8ec10dc1-d526-4723-80e7-00f4766d3825/a/paYDKA0)

**Comment by looper-m** [comment]
Links to Privacy page, GitHub repo and text to be fed as props to Footer layout component
