### ISSUE TITLE
Create account menu

### ISSUE THREAD

**Issue by alecherryy** [alecherryy/cooks-books-app#14]

**Comment by rileyhgrant** [comment]
Whats the best way to go about making the selected item have the styling on the mockups? Any and all input is appreciated, I really don't have a good idea of which direction to go with that. Attached is a screenshot of where its at currently.

<img width="273" alt="Screen Shot 2021-03-25 at 1 47 32 PM" src="https://user-images.githubusercontent.com/59549713/112475191-eb4f4500-8d46-11eb-96d8-fa7ad5888285.png">
