### ISSUE TITLE
Create Carousel component

### ISSUE THREAD

**Issue by alecherryy** [alecherryy/cooks-books-app#16]
Install and set up a Carousel component using the [SwiperJS](https://swiperjs.com/react) library. The component shall include the following fields:
1. Slides
2. Arrow Controls

The arrow controls should match the design styles and slides should rotate in an infinite loop.

Design reference: [https://www.sketch.com/s/8ec10dc1-d526-4723-80e7-00f4766d3825/a/L0JAwKy](https://www.sketch.com/s/8ec10dc1-d526-4723-80e7-00f4766d3825/a/L0JAwKy)

**Comment by looper-m** [comment]
There are some known issues with SwiperJS loops. It works (rather poorly) with 5 or more cards.
