### ISSUE TITLE
Create Header

### ISSUE THREAD

**Issue by alecherryy** [alecherryy/cooks-books-app#8]
The Header layout shall includes a Logo component, a Link to the Search page and a button link to the Login page.

Sketch: [Component](https://www.sketch.com/s/8ec10dc1-d526-4723-80e7-00f4766d3825/a/dlgYj1E)
Sketch: [Page](https://www.sketch.com/s/8ec10dc1-d526-4723-80e7-00f4766d3825/a/paYDKA0)

**Comment by looper-m** [comment]
Do we have CookBooks vector graphics? I was hoping to hard set the left content of header with this logo.
